version: '3'

services:
  flask-app:
    build: .
    ports:
     - "5001:5000"
    volumes:
     - .:/app
    depends_on:
      - mysql
    environment:
      - YOUTUBE_API_BASE_URL=https://www.googleapis.com/youtube/v3/search
      - API_KEY=AIzaSyCWwKUkm6ENnEEao3agXpteS9UBWRkv41w
      - BACK_UP_API_KEY=AIzaSyBWmLz7Yd5GOjddPyf-IhyCUTGMTu_nvEM
      - QUERY = modi
      - MYSQL_HOST=mysql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin 
      - MYSQL_DATABASE=test

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin
      - MYSQL_DATABASE=test
      - MYSQL_ROOT_PASSWORD=admin

    ports:
      - "3306:3306"
